WebServer:
  isActive: true
  host: localhost
  port: 8484
Service:
  host: localhost.dev
  port: 88
  user: user-name.dev
WriteLogDataBase:
  host: database.cloud.example.dev
  port: 9202
  user: log_writer.dev
  namedb:
  storage_name_db: application_template_db.dev
