WebServer:
  isActive: true
  host: localhost
  port: 8484
Service:
  host: localhost
  port: 80
  user: user-name
WriteLogDataBase:
  host: database.cloud.example
  port: 9200
  user: log_writer
  namedb:
  storage_name_db: application_template_db
