WebServer:
  isActive: true
  host: localhost
  port: 8484
Service:
  host: localhost.dev
  port: 88
  user: user-name.dev
WriteLogDataBase:
  host: database.cloud.example.prod
  port: 9200
  user: log_writer.prod
  namedb:
  storage_name_db: application_template_db.prod
